[package]
name = "openvm-input-utils"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "gen_input"
path = "gen_input.rs"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1" }
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
